site_name: P치gina de Gerardo - Documentaci칩n
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.keys
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
# Use the ReadTheDocs theme
theme:
  name: material
  highlightjs: true 
  palette:
      - scheme: default
        primary: green

  features:
    - content.code.copy
    - content.tooltips
extra_css:
  - https://use.fontawesome.com/releases/v6.5.2/css/all.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css
  
nav:
  - Inicio: index.md
  - Con칩ceme: aboutme.md
  - Trabajos semanales:
    - Circuito con Osciloscopio: osciloscopio.md
    - Control de Motores DC con ESP32 y Puente H: controlmotores.md
    - Control de LED con ESP32: ledesp32.md
    - Control de Servos: servos.md
    - Programa con c치mara: camara.md
  - Proyectos (Coche y Plataforma):
    - Proyecto coche: proyectos.md
    - Proyecto plataforma: plataforma.md
  - Equipo de trabajo: presentacion.md 
